AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/schema.db'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'
